name: release

on:
  push:
    tags:
    - "v*.*.*"

env:
  TAG: ${{ github.ref_name }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: setupGo
      uses: actions/setup-go@v4
      with:
        go-version: '=1.19.4'
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image
      run: make docker-build-all TAG=${{ env.TAG }}
    - name: Push docker image
      run: make docker-push-all TAG=${{ env.TAG }} PROD_REGISTRY=${{ env.REGISTRY }}
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: setupGo
      uses: actions/setup-go@v4
      with:
        go-version: '=1.19.4'
    - name: Update manifests
      run: |
        make release RELEASE_TAG=${{ env.TAG }} 
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        discussion_category_name: Announcements
        name: ${{ env.TAG }}
        files: |
          out/metadata.yaml
          out/bootstrap-components.yaml
          out/control-plane-components.yaml